import httpx

from app.config import settings
from app.nim import LLMGateway


def test_gateway_uses_deterministic_fallback_without_keys(monkeypatch):
    for name in ('nim_api_key', 'openrouter_api_key', 'groq_api_key', 'gemini_api_key'):
        monkeypatch.setattr(settings, name, None)
    result = LLMGateway().generate('system', 'user', fallback='safe fallback', purpose='test')
    assert result.text == 'safe fallback'
    assert result.mode == 'FALLBACK'
    assert all(attempt['status'] == 'SKIPPED' for attempt in result.attempts)


def test_gateway_fails_over_to_next_healthy_provider(monkeypatch):
    monkeypatch.setattr(settings, 'llm_provider_priority', 'nvidia,groq,gemini,openrouter')
    monkeypatch.setattr(settings, 'nim_api_key', 'test-nvidia')
    monkeypatch.setattr(settings, 'groq_api_key', 'test-groq')
    monkeypatch.setattr(settings, 'gemini_api_key', None)
    monkeypatch.setattr(settings, 'openrouter_api_key', None)
    gateway = LLMGateway()

    def fake_openai(provider, system, user):
        if provider.id == 'nvidia':
            request = httpx.Request('POST', 'https://example.invalid/chat/completions')
            response = httpx.Response(429, request=request)
            raise httpx.HTTPStatusError('rate limited', request=request, response=response)
        return 'Generated by the fallback provider.', provider.model

    monkeypatch.setattr(gateway, '_openai_chat', fake_openai)
    result = gateway.generate('system', 'user', fallback='safe fallback', purpose='test')
    assert result.mode == 'LIVE'
    assert result.provider == 'groq'
    assert result.text == 'Generated by the fallback provider.'
    assert result.attempts == [
        {'provider': 'nvidia', 'status': 'FAILED', 'error': 'HTTP_429'},
        {'provider': 'groq', 'status': 'SUCCESS'},
    ]


def test_gateway_can_route_a_stage_to_a_preferred_provider(monkeypatch):
    monkeypatch.setattr(settings, 'llm_provider_priority', 'nvidia,groq,gemini,openrouter')
    monkeypatch.setattr(settings, 'nim_api_key', 'test-nvidia')
    monkeypatch.setattr(settings, 'groq_api_key', 'test-groq')
    monkeypatch.setattr(settings, 'gemini_api_key', None)
    monkeypatch.setattr(settings, 'openrouter_api_key', None)
    gateway = LLMGateway()
    monkeypatch.setattr(gateway, '_openai_chat', lambda provider, system, user: ('ok', provider.model))
    result = gateway.generate('system', 'user', fallback='fallback', preferred_provider='groq')
    assert result.provider == 'groq'
    assert result.attempts == [{'provider': 'groq', 'status': 'SUCCESS'}]
