import { BookOpenCheck, FlaskConical, GraduationCap, Send, Target } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';

import { Empty, Loading, MetricCard, Notice, PageHeader, Progress, StatusPill } from '../components/ui';
import { useAuth } from '../features/auth/AuthContext';
import { api, jsonBody } from '../services/api';

function useToken(){const {token}=useAuth();return token;}
type Dashboard={profile:{id:number;name:string;institution:string;department:string;designation:string;expertise:string[];interests:string[]};opportunities:any[];curriculum_insights:any[]};

export function AcademicianDashboardPage(){const token=useToken();const [data,setData]=useState<Dashboard|null>(null);useEffect(()=>{void api<Dashboard>('/sih/academician/dashboard',{token}).then(setData)},[]);if(!data)return <Loading/>;const high=data.opportunities.filter(x=>x.match_score>=60).length;return <><PageHeader eyebrow="Academician workspace" title={`Welcome, ${data.profile.name}`} description="Connect faculty expertise to FDP, research and consultancy opportunities while using real hiring outcomes to strengthen curriculum."/><div className="grid gap-4 sm:grid-cols-3"><MetricCard label="Matched opportunities" value={data.opportunities.length}/><MetricCard label="Strong expertise matches" value={high}/><MetricCard label="Curriculum signals" value={data.curriculum_insights.length}/></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="surface p-6"><div className="flex items-center gap-2"><GraduationCap className="h-5 w-5 text-sky-700"/><h2 className="section-title">Best faculty opportunities</h2></div><div className="mt-4 space-y-3">{data.opportunities.slice(0,4).map(x=><div className="rounded-xl border border-slate-200 p-4" key={x.id}><div className="flex items-start justify-between gap-4"><div><span className="badge">{x.opportunity_type}</span><p className="mt-2 font-semibold text-slate-950">{x.title}</p><p className="mt-1 text-sm text-slate-500">{x.host_name} · {x.mode}</p></div><div className="text-xl font-semibold text-slate-900">{x.match_score}%</div></div></div>)}</div></section><section className="surface p-6"><div className="flex items-center gap-2"><Target className="h-5 w-5 text-sky-700"/><h2 className="section-title">Curriculum signals</h2></div><div className="mt-4 space-y-4">{data.curriculum_insights.slice(0,5).map((x,i)=><div key={`${x.skill}-${i}`}><div className="flex items-center justify-between text-sm"><span className="font-medium text-slate-700">{x.skill}</span><span className="text-slate-500">{x.gap_percent}% gap</span></div><div className="mt-2"><Progress value={x.gap_percent}/></div></div>)}</div></section></div></>}

export function AcademicianOpportunitiesPage(){const token=useToken();const [data,setData]=useState<Dashboard|null>(null);const [message,setMessage]=useState('');const load=()=>api<Dashboard>('/sih/academician/dashboard',{token}).then(setData);useEffect(()=>{void load()},[]);async function apply(id:number){await api(`/sih/academician/opportunities/${id}/apply`,{method:'POST',token});setMessage('Application submitted. The opportunity now remains linked to your academician profile.');await load()}if(!data)return <Loading/>;return <><PageHeader eyebrow="Academician opportunities" title="FDP, research & consultancy" description="A dedicated opportunity layer extends the same skill/expertise matching philosophy beyond student internships and placements."/>{message?<div className="mb-5"><Notice tone="success">{message}</Notice></div>:null}<div className="grid gap-4 lg:grid-cols-2">{data.opportunities.map(x=><div className="surface surface-hover p-6" key={x.id}><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2"><span className="badge">{x.opportunity_type}</span><span className="badge">{x.mode}</span>{x.applied?<StatusPill value="APPLIED"/>:null}</div><h2 className="mt-3 text-lg font-semibold text-slate-950">{x.title}</h2><p className="mt-1 text-sm text-slate-500">{x.host_name} · {x.location}</p></div><div className="text-right"><div className="text-3xl font-semibold text-slate-950">{x.match_score}%</div><div className="text-xs text-slate-500">expertise match</div></div></div><p className="mt-4 text-sm leading-6 text-slate-600">{x.description}</p><div className="mt-4 flex flex-wrap gap-2">{x.required_expertise.map((s:string)=><span className="badge" key={s}>{s}</span>)}</div><button className="btn-primary mt-5" disabled={x.applied} onClick={()=>void apply(x.id)} type="button"><Send className="h-4 w-4"/>{x.applied?'Applied':'Apply'}</button></div>)}</div></>}

export function AcademicianCurriculumPage(){const token=useToken();const [data,setData]=useState<Dashboard|null>(null);const [form,setForm]=useState({name:'',institution:'',department:'',designation:'',expertise:'',interests:''});const [message,setMessage]=useState('');useEffect(()=>{void api<Dashboard>('/sih/academician/dashboard',{token}).then(d=>{setData(d);setForm({name:d.profile.name,institution:d.profile.institution,department:d.profile.department,designation:d.profile.designation,expertise:d.profile.expertise.join(', '),interests:d.profile.interests.join(', ')})})},[]);async function save(e:FormEvent){e.preventDefault();await api('/sih/academician/profile',{method:'PUT',token,body:jsonBody({...form,expertise:form.expertise.split(',').map(x=>x.trim()).filter(Boolean),interests:form.interests.split(',').map(x=>x.trim()).filter(Boolean)})});setMessage('Academician expertise updated. Opportunity match scores will use the new profile.')}if(!data)return <Loading/>;return <><PageHeader eyebrow="Industry-to-curriculum loop" title="Curriculum & expertise intelligence" description="Hiring demand and company feedback become faculty-visible signals rather than a one-time survey."/>{message?<div className="mb-5"><Notice tone="success">{message}</Notice></div>:null}<div className="grid gap-6 xl:grid-cols-[.7fr_1.3fr]"><form className="surface p-6" onSubmit={save}><FlaskConical className="h-6 w-6 text-sky-700"/><h2 className="mt-3 section-title">Expertise profile</h2>{[['Name','name'],['Institution','institution'],['Department','department'],['Designation','designation'],['Expertise','expertise'],['Interests','interests']].map(([label,key])=><label className="mt-4 block" key={key}><span className="label">{label}</span><input className="input" value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<button className="btn-primary mt-5 w-full" type="submit"><BookOpenCheck className="h-4 w-4"/>Update expertise</button></form><section className="surface p-6"><h2 className="section-title">Observed skill gaps</h2><p className="mt-1 text-sm text-slate-500">Evidence count is derived from live role demand and outcome feedback.</p><div className="mt-5 space-y-4">{data.curriculum_insights.length?data.curriculum_insights.map((x,i)=><div className="rounded-xl border border-slate-200 p-4" key={`${x.skill}-${i}`}><div className="flex items-start justify-between gap-4"><div><p className="font-semibold text-slate-950">{x.skill}</p><p className="mt-1 text-xs text-slate-500">{x.department} · {x.evidence_count} evidence signal(s)</p></div><span className="text-lg font-semibold text-slate-900">{x.gap_percent}%</span></div><p className="mt-3 text-sm leading-6 text-slate-600">{x.recommendation}</p></div>):<Empty title="No curriculum signals yet" description="Signals appear as companies publish roles and submit outcome feedback."/>}</div></section></div></>}
