import { BookOpenCheck, Check, ChevronRight, CircleCheckBig, FileBadge2, RefreshCw, SearchCheck, Send, Sparkles, Target, UploadCloud } from 'lucide-react';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';

import { Empty, Loading, MetricCard, Notice, PageHeader, Progress, StatusPill } from '../components/ui';
import { useAuth } from '../features/auth/AuthContext';
import { api, jsonBody } from '../services/api';
import type { Allocation, LearningRecommendation, LSRW, Opportunity, StudentDashboard, StudentProfile } from '../types/api';

function useToken() {
  const { token } = useAuth();
  if (!token) throw new Error('Missing session');
  return token;
}

export function StudentDashboardPage() {
  const token = useToken();
  const [data, setData] = useState<StudentDashboard | null>(null);
  const [provider, setProvider] = useState<Record<string, unknown> | null>(null);
  const [error, setError] = useState('');
  const [running, setRunning] = useState(false);
  const [agentNotice, setAgentNotice] = useState<{ tone: 'success' | 'info' | 'error'; text: string } | null>(null);
  const load = () => api<StudentDashboard>('/sih/student/dashboard', { token }).then(setData).catch((e) => setError(e.message));
  useEffect(() => { void load(); void api<Record<string, unknown>>('/sih/system/provider').then(setProvider); }, []);
  if (!data && !error) return <Loading />;
  if (!data) return <Notice tone="error">{error}</Notice>;
  const matchRows = data.top_matches as Array<Record<string, any>>;
  async function runAgents() { setRunning(true); setAgentNotice(null); try { const runs = await api<Array<{status:string}>>('/sih/student/agents/run', { method: 'POST', token }); const failed = runs.filter((item) => item.status === 'FAILED').length; const live = runs.filter((item) => item.status === 'COMPLETED').length; setAgentNotice(failed ? { tone: 'error', text: `${failed} agent stage(s) failed. Open Agent activity for details.` } : live === runs.length ? { tone: 'success', text: 'All six agents completed with live LLM reasoning.' } : { tone: 'info', text: 'All six deterministic checks completed; unavailable LLM stages used transparent fallback reasoning.' }); await load(); } catch (e) { setAgentNotice({ tone: 'error', text: e instanceof Error ? e.message : 'Unable to run agents' }); } finally { setRunning(false); } }
  return <>
    <PageHeader eyebrow="Student workspace" title={`Welcome, ${data.profile.name}`} description="Your readiness, skill gaps, communication and opportunity pipeline in one place." actions={<button className="btn-soft" onClick={() => void runAgents()} disabled={running} type="button"><Sparkles className="h-4 w-4" />{running ? 'Running agents…' : 'Run 6-agent cycle'}</button>} />
    {agentNotice ? <div className="mb-5"><Notice tone={agentNotice.tone}>{agentNotice.text}</Notice></div> : null}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <MetricCard label="Profile strength" value={`${data.profile.profile_completion}%`} detail={<Progress value={data.profile.profile_completion} />} />
      <MetricCard label="Industry readiness" value={`${data.readiness}%`} detail="Average of your strongest current matches" />
      <MetricCard label="Communication" value={data.communication ? `${data.communication.overall}%` : 'Not assessed'} detail="LSRW overall score" />
      <MetricCard label="Active offers" value={data.offers.filter((item) => item.status === 'OFFERED').length} detail={`${data.applications.length} applications submitted`} />
    </div>

    <div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.65fr]">
      <section className="surface p-5 sm:p-6">
        <div className="flex items-center justify-between"><div><h2 className="section-title">Best-fit opportunities</h2><p className="mt-1 text-sm text-slate-500">Ranked by deterministic skill, readiness and preference signals.</p></div><Link to="/student/opportunities" className="text-sm font-semibold text-sky-700">View all</Link></div>
        <div className="mt-5 space-y-3">
          {matchRows.slice(0, 4).map((match) => {
            const opp = match.opportunity ?? {};
            return <div className="rounded-xl border border-slate-200 p-4" key={match.id}><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-slate-900">{opp.title ?? `Opportunity #${match.opportunity_id}`}</p><span className="badge">{opp.opportunity_type ?? 'Opportunity'}</span></div><p className="mt-1 text-sm text-slate-500">{opp.company_name ?? ''} · {opp.location ?? ''} · {opp.work_mode ?? ''}</p></div><div className="min-w-24 text-right"><div className="text-2xl font-semibold text-slate-950">{match.total_score}%</div><div className="text-xs text-slate-500">match</div></div></div><div className="mt-3"><Progress value={match.total_score} /></div></div>;
          })}
        </div>
      </section>
      <section className="space-y-6">
        <div className="surface p-5 sm:p-6"><h2 className="section-title">Next actions</h2><div className="mt-4 space-y-3">{data.learning.slice(0, 3).map((item) => <div className="flex gap-3" key={item.id}><div className="mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-sky-50 text-sky-700"><BookOpenCheck className="h-4 w-4" /></div><div><p className="text-sm font-semibold text-slate-900">{item.skill}</p><p className="mt-1 text-xs leading-5 text-slate-500">{item.reason}</p></div></div>)}</div><Link className="btn-secondary mt-5 w-full" to="/student/learning">Open learning path</Link></div>
        <div className="surface p-5"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-slate-900">AI provider</p><p className="mt-1 text-xs text-slate-500">Recommendations and explanations only</p></div><StatusPill value={String(provider?.mode ?? 'Fallback')} /></div><p className="mt-4 text-sm text-slate-600">{String(provider?.provider ?? 'NVIDIA NIM')} · {String(provider?.model ?? '')}</p></div>
      </section>
    </div>
  </>;
}

export function StudentProfilePage() {
  const token = useToken();
  const [profile, setProfile] = useState<StudentProfile | null>(null);
  const [skills, setSkills] = useState('');
  const [resumeText, setResumeText] = useState('');
  const [notice, setNotice] = useState('');
  const [error, setError] = useState('');
  useEffect(() => { void api<StudentProfile>('/sih/student/profile', { token }).then((value) => { setProfile(value); setSkills(value.skills.join(', ')); }).catch((e) => setError(e.message)); }, []);
  if (!profile && !error) return <Loading />;
  if (!profile) return <Notice tone="error">{error}</Notice>;
  async function save(event: FormEvent) { event.preventDefault(); setNotice(''); setError(''); const currentProfile = profile; if (!currentProfile) return; try { const value = await api<StudentProfile>('/sih/student/profile', { method: 'PUT', token, body: jsonBody({ ...currentProfile, skills: skills.split(',').map((x) => x.trim()).filter(Boolean), projects: currentProfile.projects, certifications: currentProfile.certifications }) }); setProfile(value); setSkills(value.skills.join(', ')); setNotice('Profile saved. Matching signals were refreshed.'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save'); } }
  async function analyzeResume() { if (resumeText.trim().length < 20) { setError('Paste at least a short resume section before analysis.'); return; } setError(''); const result = await api<{ profile: StudentProfile; extracted_skills: string[] }>('/sih/student/resume/analyze', { method: 'POST', token, body: jsonBody({ text: resumeText }) }); setProfile(result.profile); setSkills(result.profile.skills.join(', ')); setNotice(`Resume analyzed. Extracted: ${result.extracted_skills.join(', ') || 'no new canonical skills'}.`); }
  async function uploadResume(file: File | null) { if (!file) return; setError(''); const formData = new FormData(); formData.append('file', file); try { const result = await api<{ profile: StudentProfile; extracted_skills: string[]; filename: string }>('/sih/student/resume/upload', { method: 'POST', token, body: formData }); setProfile(result.profile); setSkills(result.profile.skills.join(', ')); setNotice(`${result.filename} analyzed securely. Extracted: ${result.extracted_skills.join(', ') || 'no new canonical skills'}.`); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to upload resume'); } }
  return <>
    <PageHeader eyebrow="Profile intelligence" title="Profile & resume" description="Keep one canonical profile. Resume extraction enriches the skill map, while you remain in control of the final profile." />
    {notice ? <div className="mb-5"><Notice tone="success">{notice}</Notice></div> : null}{error ? <div className="mb-5"><Notice tone="error">{error}</Notice></div> : null}
    <div className="grid gap-6 xl:grid-cols-[1fr_.8fr]">
      <form className="surface p-5 sm:p-6" onSubmit={save}><div className="flex items-center justify-between"><h2 className="section-title">Student profile</h2><span className="badge">{profile.profile_completion}% complete</span></div><div className="mt-5 grid gap-4 sm:grid-cols-2">
        {[
          ['Name','name'],['College','college'],['University','university'],['Degree','degree'],['Department','department'],['City','city'],['State','state'],['Reservation category','reservation_category']
        ].map(([label,key]) => <label key={key}><span className="label">{label}</span><input className="input" value={String((profile as any)[key] ?? '')} onChange={(e) => setProfile({ ...profile, [key]: e.target.value })} /></label>)}
        <label><span className="label">Current year</span><input className="input" type="number" min={1} max={8} value={profile.current_year} onChange={(e) => setProfile({ ...profile, current_year: Number(e.target.value) })} /></label>
        <label><span className="label">CGPA</span><input className="input" type="number" step="0.1" min={0} max={10} value={profile.cgpa} onChange={(e) => setProfile({ ...profile, cgpa: Number(e.target.value) })} /></label>
      </div><label className="mt-4 block"><span className="label">Skills</span><textarea className="input min-h-28" value={skills} onChange={(e) => setSkills(e.target.value)} placeholder="Python, FastAPI, Machine Learning, SQL" /><span className="mt-1 block text-xs text-slate-400">Comma-separated. StuSkillLink normalizes common aliases during matching.</span></label><button className="btn-primary mt-5" type="submit"><Check className="h-4 w-4" /> Save profile</button></form>
      <section className="surface p-5 sm:p-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-sky-50 text-sky-700"><UploadCloud className="h-5 w-5" /></div><div><h2 className="section-title">Resume intelligence</h2><p className="text-xs text-slate-500">Paste extracted resume text for this prototype.</p></div></div><label className="mt-5 block rounded-xl border border-dashed border-slate-300 bg-slate-50 p-4 text-center"><UploadCloud className="mx-auto h-5 w-5 text-sky-700"/><span className="mt-2 block text-sm font-semibold text-slate-800">Upload PDF, DOCX or TXT resume</span><span className="mt-1 block text-xs text-slate-500">Maximum 3 MB · executable formats are rejected</span><input className="mt-3 block w-full text-xs text-slate-500" type="file" accept=".pdf,.docx,.txt" onChange={(e)=>void uploadResume(e.target.files?.[0]??null)}/></label><div className="my-4 flex items-center gap-3"><div className="h-px flex-1 bg-slate-200"/><span className="text-xs text-slate-400">or paste text</span><div className="h-px flex-1 bg-slate-200"/></div><textarea className="input min-h-48" value={resumeText} onChange={(e) => setResumeText(e.target.value)} placeholder="Paste resume text here…" /><button className="btn-soft mt-4 w-full" onClick={() => void analyzeResume()} type="button"><Sparkles className="h-4 w-4" /> Analyze and map skills</button><div className="mt-5 rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-500">The deterministic parser identifies canonical skill terms. NVIDIA NIM can enrich recommendations while core ranking remains deterministic.</div></section>
    </div>
  </>;
}

export function StudentSkillGapPage() {
  const token = useToken(); const [data,setData]=useState<any>(null); const [error,setError]=useState('');
  useEffect(()=>{ void api('/sih/student/skill-gap',{token}).then(setData).catch((e)=>setError(e.message)); },[]);
  if(!data&&!error)return <Loading/>; if(!data)return <Notice tone="error">{error}</Notice>;
  return <><PageHeader eyebrow="Skill intelligence" title="Skill-gap report" description="Your current skills are compared against the strongest live opportunity matches—not a generic static checklist."/><div className="grid gap-4 sm:grid-cols-3"><MetricCard label="Role readiness" value={`${data.readiness}%`} detail="Across top role matches"/><MetricCard label="Current strengths" value={data.strongest_skills.length} detail="Canonical skills in profile"/><MetricCard label="Priority gaps" value={data.priority_gaps.length} detail="Demand-backed missing skills"/></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="surface p-6"><h2 className="section-title">Strengths</h2><div className="mt-4 flex flex-wrap gap-2">{data.strongest_skills.map((skill:string)=><span className="badge" key={skill}>{skill}</span>)}</div></section><section className="surface p-6"><h2 className="section-title">Priority gaps</h2><div className="mt-4 space-y-3">{data.priority_gaps.map((gap:any)=><div className="flex items-center justify-between rounded-xl border border-slate-200 p-4" key={gap.skill}><div><p className="font-semibold text-slate-900">{gap.skill}</p><p className="mt-1 text-xs text-slate-500">Required by {gap.demand_count} of your strongest matched roles</p></div><StatusPill value={gap.priority}/></div>)}</div></section></div><div className="mt-6"><Link className="btn-primary" to="/student/learning">Turn gaps into learning actions <ChevronRight className="h-4 w-4"/></Link></div></>;
}

export function StudentLSRWPage() {
  const token=useToken();
  const [result,setResult]=useState<LSRW|null>(null);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  const [listeningAnswers,setListeningAnswers]=useState(['','','']);
  const [readingAnswers,setReadingAnswers]=useState(['','','']);
  const [speakingText,setSpeakingText]=useState('');
  const [writingText,setWritingText]=useState('');
  const listeningPassage='A student team built a low-cost air quality monitor. They tested the sensor in three classrooms, compared readings with a reference device, and improved calibration before presenting the prototype to an industry mentor.';
  const readingPassage='Industry-ready learning improves when academic programs use evidence from real roles. Skill requirements can change faster than a syllabus cycle, so institutions benefit from seeing repeated hiring gaps, internship feedback, and placement outcomes together. Students also benefit when the same verified portfolio follows them from learning into internship and placement.';
  const listeningQuestions=[
    {q:'What did the team build?',options:['A mobile game','An air quality monitor','A payment system'],answer:'An air quality monitor'},
    {q:'Where did they test it?',options:['Three classrooms','A railway station','Two factories'],answer:'Three classrooms'},
    {q:'What did they improve before presenting?',options:['Calibration','Advertising','Packaging'],answer:'Calibration'},
  ];
  const readingQuestions=[
    {q:'What evidence helps institutions improve curriculum?',options:['Only exam marks','Hiring gaps, internship feedback and placement outcomes','Only attendance'],answer:'Hiring gaps, internship feedback and placement outcomes'},
    {q:'Why is continuous evidence useful?',options:['Skill requirements can change quickly','Syllabi never change','Companies use no skills'],answer:'Skill requirements can change quickly'},
    {q:'What follows the student across the lifecycle?',options:['A verified portfolio','A different profile for every step','Only a hall ticket'],answer:'A verified portfolio'},
  ];
  function speakPrompt(){if(!('speechSynthesis' in window)){setError('Browser text-to-speech is unavailable. Use a Chromium-based browser for the listening demo.');return;}window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(listeningPassage);utterance.rate=0.9;window.speechSynthesis.speak(utterance);}
  function startDictation(){const w=window as any;const Recognition=w.SpeechRecognition||w.webkitSpeechRecognition;if(!Recognition){setError('Browser speech recognition is unavailable. Type your speaking transcript instead.');return;}setError('');const recognition=new Recognition();recognition.lang='en-IN';recognition.interimResults=false;recognition.maxAlternatives=1;recognition.onresult=(event:any)=>setSpeakingText(event.results?.[0]?.[0]?.transcript??'');recognition.onerror=()=>setError('Speech recognition could not capture the response. You can type the transcript instead.');recognition.start();}
  async function submit(e:FormEvent){e.preventDefault();const listeningCorrect=listeningQuestions.filter((x,i)=>listeningAnswers[i]===x.answer).length;const readingCorrect=readingQuestions.filter((x,i)=>readingAnswers[i]===x.answer).length;if(speakingText.trim().length<20||writingText.trim().length<20){setError('Complete the speaking and writing responses before submitting.');return;}setBusy(true);setError('');try{setResult(await api<LSRW>('/sih/student/lsrw/assess',{method:'POST',token,body:jsonBody({listening_correct:listeningCorrect,listening_total:listeningQuestions.length,reading_correct:readingCorrect,reading_total:readingQuestions.length,speaking_text:speakingText,writing_text:writingText})}));}catch(err){setError(err instanceof Error?err.message:'Assessment failed');}finally{setBusy(false)}}
  return <><PageHeader eyebrow="Communication readiness" title="LSRW assessment" description="Complete listening, speaking, reading and writing in one guided flow. Objective sections are auto-graded; speaking and writing use a transparent rubric."/>{error?<div className="mb-5"><Notice tone="error">{error}</Notice></div>:null}<form className="space-y-6" onSubmit={submit}>
    <section className="surface p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow">01 · Listening</p><h2 className="mt-1 section-title">Listen once, then answer</h2></div><button className="btn-secondary" onClick={speakPrompt} type="button"><Send className="h-4 w-4"/>Play prompt</button></div><div className="mt-5 grid gap-4 lg:grid-cols-3">{listeningQuestions.map((item,i)=><div className="rounded-xl bg-slate-50 p-4" key={item.q}><p className="text-sm font-semibold text-slate-900">{item.q}</p><div className="mt-3 space-y-2">{item.options.map(option=><label className="flex cursor-pointer items-start gap-2 text-sm text-slate-600" key={option}><input className="mt-1" type="radio" name={`listening-${i}`} checked={listeningAnswers[i]===option} onChange={()=>{const next=[...listeningAnswers];next[i]=option;setListeningAnswers(next)}}/><span>{option}</span></label>)}</div></div>)}</div></section>
    <section className="surface p-6"><p className="eyebrow">02 · Speaking</p><div className="mt-1 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="section-title">Explain one project in about 60 seconds</h2><p className="mt-1 text-sm text-slate-500">Describe the problem, your contribution, tools used and outcome.</p></div><button className="btn-secondary shrink-0" onClick={startDictation} type="button"><Sparkles className="h-4 w-4"/>Use microphone</button></div><textarea className="input mt-5 min-h-32" value={speakingText} onChange={e=>setSpeakingText(e.target.value)} placeholder="Your speech transcript appears here, or type it manually…"/></section>
    <section className="surface p-6"><p className="eyebrow">03 · Reading</p><h2 className="mt-1 section-title">Read and understand</h2><div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm leading-7 text-slate-700">{readingPassage}</div><div className="mt-5 grid gap-4 lg:grid-cols-3">{readingQuestions.map((item,i)=><div className="rounded-xl border border-slate-200 p-4" key={item.q}><p className="text-sm font-semibold text-slate-900">{item.q}</p><div className="mt-3 space-y-2">{item.options.map(option=><label className="flex cursor-pointer items-start gap-2 text-sm text-slate-600" key={option}><input className="mt-1" type="radio" name={`reading-${i}`} checked={readingAnswers[i]===option} onChange={()=>{const next=[...readingAnswers];next[i]=option;setReadingAnswers(next)}}/><span>{option}</span></label>)}</div></div>)}</div></section>
    <section className="surface p-6"><p className="eyebrow">04 · Writing</p><h2 className="mt-1 section-title">Why are you suitable for your preferred internship?</h2><p className="mt-1 text-sm text-slate-500">Write a concise response covering relevant skills, evidence and what you want to learn.</p><textarea className="input mt-5 min-h-40" value={writingText} onChange={e=>setWritingText(e.target.value)} placeholder="Write your response…"/></section>
    <div className="flex justify-end"><button className="btn-primary" disabled={busy} type="submit">{busy?'Scoring assessment…':'Submit LSRW assessment'}</button></div>
  </form>{result?<section className="surface mt-6 p-6"><div className="grid gap-6 lg:grid-cols-[.35fr_.65fr]"><div><p className="eyebrow">Latest result</p><div className="mt-2 text-5xl font-semibold tracking-tight text-slate-950">{result.overall}%</div><p className="mt-2 text-sm text-slate-500">Overall communication readiness</p></div><div className="space-y-4">{[['Listening',result.listening],['Speaking',result.speaking],['Reading',result.reading],['Writing',result.writing]].map(([label,value])=><Progress key={String(label)} label={String(label)} value={Number(value)}/>)}</div></div></section>:null}</>;
}
export function StudentLearningPage(){
  const token=useToken(); const [items,setItems]=useState<LearningRecommendation[]|null>(null); const [programs,setPrograms]=useState<any[]|null>(null); const [error,setError]=useState('');
  const load=()=>Promise.all([api<LearningRecommendation[]>('/sih/student/learning',{token}),api<any[]>('/sih/student/industry-learning',{token})]).then(([a,b])=>{setItems(a);setPrograms(b)}).catch(e=>setError(e.message)); useEffect(()=>{void load()},[]);
  async function complete(id:number){await api(`/sih/student/learning/${id}/complete`,{method:'POST',token});await load()}
  async function completeProgram(id:number){await api(`/sih/student/industry-learning/${id}/complete`,{method:'POST',token});await load()}
  if((!items||!programs)&&!error)return <Loading/>; if(!items||!programs)return <Notice tone="error">{error}</Notice>;
  return <><PageHeader eyebrow="Actionable learning path" title="Close the gaps that matter" description="Demand-backed recommendations and industry-led programs connect skill development directly to your verified portfolio."/><div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><section><div className="mb-3"><h2 className="section-title">Your priority skill gaps</h2><p className="mt-1 text-sm text-slate-500">Generated from the strongest current opportunity matches.</p></div><div className="space-y-4">{items.length?items.map(item=><div className="surface p-5" key={item.id}><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-slate-950">{item.skill}</h3><StatusPill value={item.completed?'COMPLETED':item.priority}/></div><p className="mt-2 text-sm text-slate-500">{item.reason}</p><p className="mt-3 text-sm leading-6 text-slate-700">{item.action}</p><a className="mt-3 inline-flex text-sm font-semibold text-sky-700" href={item.resource_url} target="_blank" rel="noreferrer">Open learning resource</a></div>{item.completed?<div className="flex items-center gap-2 text-sm font-semibold text-emerald-700"><CircleCheckBig className="h-5 w-5"/>Portfolio badge issued</div>:<button className="btn-primary shrink-0" onClick={()=>void complete(item.id)} type="button"><Check className="h-4 w-4"/>Mark complete</button>}</div></div>):<Empty title="No priority gaps" description="Your strongest matches currently have no high-priority missing skills."/>}</div></section><section><div className="mb-3"><h2 className="section-title">Industry-led programs</h2><p className="mt-1 text-sm text-slate-500">Programs published by participating companies and linked to verifiable portfolio badges.</p></div><div className="space-y-4">{programs.map(program=><div className="surface p-5" key={program.id}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-slate-950">{program.title}</p><p className="mt-1 text-xs text-slate-500">{program.provider} · {program.duration}</p></div><span className="badge">{program.relevance}% relevant</span></div><div className="mt-3 flex flex-wrap gap-2">{program.skills.map((skill:string)=><span className="badge" key={skill}>{skill}</span>)}</div>{program.completed?<div className="mt-4 flex items-center gap-2 text-sm font-semibold text-emerald-700"><CircleCheckBig className="h-4 w-4"/>Verified badge in portfolio</div>:<button className="btn-secondary mt-4" onClick={()=>void completeProgram(program.id)} type="button"><FileBadge2 className="h-4 w-4"/>Complete demo program</button>}</div>)}</div></section></div></>;
}
export function StudentPortfolioPage(){
  const token=useToken(); const [data,setData]=useState<any>(null); useEffect(()=>{void api('/sih/student/portfolio',{token}).then(setData)},[]); if(!data)return <Loading/>;
  return <><PageHeader eyebrow="Verified digital portfolio" title="Evidence that travels with you" description="Projects, certifications, communication readiness and industry-linked badges stay attached to the same student profile across internships and placements."/><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><section className="surface p-6"><h2 className="section-title">Profile snapshot</h2><div className="mt-5"><div className="text-2xl font-semibold text-slate-950">{data.profile.name}</div><p className="mt-1 text-sm text-slate-500">{data.profile.degree} · {data.profile.department}</p><div className="mt-5 flex flex-wrap gap-2">{data.profile.skills.map((s:string)=><span className="badge" key={s}>{s}</span>)}</div></div></section><section className="surface p-6"><div className="flex items-center justify-between"><h2 className="section-title">Verified badges</h2><FileBadge2 className="h-5 w-5 text-sky-700"/></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{data.badges.map((b:any)=><div className="rounded-xl border border-slate-200 p-4" key={b.id}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-slate-900">{b.title}</p><p className="mt-1 text-xs text-slate-500">{b.issuer}</p></div>{b.verified?<CircleCheckBig className="h-5 w-5 text-emerald-600"/>:null}</div></div>)}</div></section></div><div className="mt-6 grid gap-6 md:grid-cols-2"><section className="surface p-6"><h2 className="section-title">Projects</h2><div className="mt-4 space-y-3">{data.profile.projects.map((p:any,index:number)=><div className="rounded-xl bg-slate-50 p-4" key={index}><p className="font-semibold text-slate-900">{String(p.title??'Project')}</p><p className="mt-1 text-sm text-slate-500">{String(p.description??'')}</p></div>)}</div></section><section className="surface p-6"><h2 className="section-title">Communication evidence</h2>{data.lsrw?<div className="mt-5"><div className="text-4xl font-semibold text-slate-950">{data.lsrw.overall}%</div><p className="mt-1 text-sm text-slate-500">Latest LSRW overall</p></div>:<p className="mt-4 text-sm text-slate-500">Complete LSRW to add communication evidence.</p>}</section></div></>;
}

export function StudentOpportunitiesPage(){
  const token=useToken(); const [items,setItems]=useState<Opportunity[]|null>(null); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [applying,setApplying]=useState<number|null>(null); const [filter,setFilter]=useState('ALL');
  const load=()=>api<Opportunity[]>('/sih/student/opportunities',{token}).then(setItems); useEffect(()=>{void load()},[]); const visible=useMemo(()=>items?.filter(x=>filter==='ALL'||x.opportunity_type===filter)??[],[items,filter]); if(!items)return <Loading/>;
  async function apply(id:number){setApplying(id);setError('');try{await api(`/sih/student/opportunities/${id}/apply`,{method:'POST',token});setMessage('Application submitted and added to the company-wise ranking pool.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to submit application')}finally{setApplying(null)}}
  return <><PageHeader eyebrow="Preference-aware discovery" title="Internships & placements" description="AI ranks what you see; it does not hide opportunities or make hiring decisions. Open roles remain browseable and every match is explainable." actions={<div className="flex rounded-xl border border-slate-200 bg-white p-1">{['ALL','INTERNSHIP','PLACEMENT'].map(x=><button onClick={()=>setFilter(x)} className={`rounded-lg px-3 py-1.5 text-xs font-semibold ${filter===x?'bg-slate-950 text-white':'text-slate-500'}`} key={x} type="button">{x==='ALL'?'All':x.toLowerCase()}</button>)}</div>}/>{message?<div className="mb-5"><Notice tone="success">{message}</Notice></div>:null}{error?<div className="mb-5"><Notice tone="error">{error}</Notice></div>:null}<div className="grid gap-4 lg:grid-cols-2">{visible.map(item=><div className="surface surface-hover p-5 sm:p-6" key={item.id}><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><span className="badge">{item.opportunity_type}</span><span className="badge">{item.work_mode}</span>{item.applied?<StatusPill value="APPLIED"/>:null}</div><h2 className="mt-3 text-lg font-semibold text-slate-950">{item.title}</h2><p className="mt-1 text-sm text-slate-500">{item.company_name} · {item.location}</p></div><div className="text-right"><div className="text-3xl font-semibold text-slate-950">{item.match?.total_score??0}%</div><div className="text-xs text-slate-500">match</div></div></div><p className="mt-4 text-sm leading-6 text-slate-600">{item.description}</p><div className="mt-4"><Progress value={item.match?.required_coverage??0} label="Required skill coverage"/></div><div className="mt-4 flex flex-wrap gap-2">{item.required_skills.map(skill=><span className="badge" key={skill}>{skill}</span>)}</div>{item.match?.explanation?.missing_required?.length?<div className="mt-4 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">Gap: {item.match.explanation.missing_required.join(', ')}</div>:null}<div className="mt-5 flex items-center justify-between gap-3"><div className="text-xs text-slate-500">{item.seats} seats · {item.stipend?`₹${item.stipend.toLocaleString()}/month`:'Salary disclosed during placement'} · deadline {item.deadline}</div><button className="btn-primary shrink-0" disabled={item.applied||applying===item.id} onClick={()=>void apply(item.id)} type="button">{item.applied?'Applied':applying===item.id?'Applying…':'Apply'}</button></div></div>)}</div></>;
}

export function StudentOffersPage(){
  const token=useToken(); const [data,setData]=useState<StudentDashboard|null>(null); const [notice,setNotice]=useState(''); const [letter,setLetter]=useState<any|null>(null); const load=()=>api<StudentDashboard>('/sih/student/dashboard',{token}).then(setData); useEffect(()=>{void load()},[]); if(!data)return <Loading/>;
  async function respond(id:number,response:'ACCEPTED'|'REJECTED'){await api(`/sih/student/offers/${id}/respond`,{method:'POST',token,body:jsonBody({response})});setNotice(response==='ACCEPTED'?'Offer accepted. Placement continuity is now updated.':'Offer rejected. The vacant seat was sent into automatic reallocation.');await load()}
  async function openLetter(id:number){setLetter(await api(`/sih/student/offers/${id}/letter`,{token}));}
  return <><PageHeader eyebrow="Transparent allocation" title="Offers & continuous reallocation" description="Every offer shows rank, allocation round and category slot. Rejected seats are automatically offered to the next eligible ranked candidate."/>{notice?<div className="mb-5"><Notice tone="success">{notice}</Notice></div>:null}<div className="space-y-4">{data.offers.length?data.offers.map((offer:Allocation)=><div className="surface p-5 sm:p-6" key={offer.id}><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-slate-950">{offer.title}</h2><StatusPill value={offer.status}/></div><p className="mt-1 text-sm text-slate-500">{offer.company_name}</p><div className="mt-3 flex flex-wrap gap-2"><span className="badge">Company rank #{offer.rank}</span><span className="badge">Allocation round {offer.round}</span><span className="badge">{offer.category_slot} slot</span></div></div><div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>void openLetter(offer.id)} type="button">Offer letter</button>{offer.status==='OFFERED'?<><button className="btn-secondary" onClick={()=>void respond(offer.id,'REJECTED')} type="button">Reject</button><button className="btn-primary" onClick={()=>void respond(offer.id,'ACCEPTED')} type="button">Accept</button></>:null}</div></div></div>):<Empty title="No allocation history" description="Apply to opportunities and enter the company-wise ranking pool to receive offers."/>}</div>{letter?<div className="surface mt-6 p-6"><div className="flex items-center justify-between gap-4"><div><p className="eyebrow">Automated offer letter</p><h2 className="mt-1 section-title">{letter.title}</h2></div><button className="btn-secondary" onClick={()=>setLetter(null)} type="button">Close</button></div><pre className="mt-5 whitespace-pre-wrap rounded-xl bg-slate-50 p-5 font-sans text-sm leading-7 text-slate-700">{letter.letter_text}</pre></div>:null}</>;
}

export function StudentPreferencesPage(){
  const token=useToken();
  const [profile,setProfile]=useState<StudentProfile|null>(null);
  const [opportunities,setOpportunities]=useState<Opportunity[]>([]);
  const [domains,setDomains]=useState('');
  const [locations,setLocations]=useState('');
  const [workModes,setWorkModes]=useState<string[]>([]);
  const [ranked,setRanked]=useState<number[]>([]);
  const [generalPool,setGeneralPool]=useState(true);
  const [message,setMessage]=useState('');
  useEffect(()=>{void Promise.all([api<StudentProfile>('/sih/student/profile',{token}),api<Opportunity[]>('/sih/student/opportunities',{token})]).then(([p,o])=>{setProfile(p);setOpportunities(o);const prefs=(p.preferences??{}) as any;setDomains((prefs.preferred_domains??[]).join(', '));setLocations((prefs.preferred_locations??[]).join(', '));setWorkModes(prefs.work_modes??[]);setRanked((prefs.ranked_opportunity_ids??[]).map(Number));setGeneralPool(p.general_pool_opt_in);})},[]);
  if(!profile)return <Loading/>;
  function setRank(index:number,value:number){const next=[...ranked];next[index]=value;setRanked(next.filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i));}
  async function save(e:FormEvent){e.preventDefault();await api('/sih/student/preferences',{method:'PUT',token,body:jsonBody({preferred_domains:domains.split(',').map(x=>x.trim()).filter(Boolean),preferred_locations:locations.split(',').map(x=>x.trim()).filter(Boolean),work_modes:workModes,ranked_opportunity_ids:ranked,ranked_company_ids:[],general_pool_opt_in:generalPool})});setMessage('Preferences saved. Match ordering and company-wise preference signals were refreshed.');}
  return <><PageHeader eyebrow="Preference-aware matching" title="Your opportunity preferences" description="You control preferred domains, locations, work modes and ranked roles. StuSkillLink uses them as visible ranking signals rather than silently filtering opportunities."/>{message?<div className="mb-5"><Notice tone="success">{message}</Notice></div>:null}<form className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]" onSubmit={save}><section className="surface p-6"><h2 className="section-title">Fit preferences</h2><label className="mt-5 block"><span className="label">Preferred domains</span><input className="input" value={domains} onChange={e=>setDomains(e.target.value)} placeholder="AI, Backend, Data Science"/></label><label className="mt-4 block"><span className="label">Preferred locations</span><input className="input" value={locations} onChange={e=>setLocations(e.target.value)} placeholder="Chennai, Bengaluru, Remote"/></label><div className="mt-4"><span className="label">Work modes</span><div className="flex flex-wrap gap-2">{['REMOTE','HYBRID','ONSITE'].map(mode=><button className={workModes.includes(mode)?'btn-primary':'btn-secondary'} onClick={()=>setWorkModes(workModes.includes(mode)?workModes.filter(x=>x!==mode):[...workModes,mode])} type="button" key={mode}>{mode.toLowerCase()}</button>)}</div></div><label className="mt-5 flex items-start gap-3 rounded-xl border border-slate-200 p-4"><input className="mt-1" checked={generalPool} onChange={e=>setGeneralPool(e.target.checked)} type="checkbox"/><span><span className="block text-sm font-semibold text-slate-900">Opt into general pool</span><span className="mt-1 block text-xs leading-5 text-slate-500">If your preferred companies are unavailable, allow matching to other suitable opportunities. You can turn this off.</span></span></label></section><section className="surface p-6"><h2 className="section-title">Rank preferred opportunities</h2><p className="mt-1 text-sm text-slate-500">Your ranked choices become an auditable preference signal and tie-break input.</p><div className="mt-5 space-y-4">{[0,1,2].map(index=><label key={index}><span className="label">Preference #{index+1}</span><select className="input" value={ranked[index]??''} onChange={e=>setRank(index,Number(e.target.value))}><option value="">Not set</option>{opportunities.map(o=><option key={o.id} value={o.id}>{o.title} · {o.company_name}</option>)}</select></label>)}</div><button className="btn-primary mt-6" type="submit"><Check className="h-4 w-4"/>Save preferences</button></section></form></>;
}
