"""initial production schema

Revision ID: fab2c8cf2285
Revises: 
Create Date: 2026-09-21 14:09:24.252253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab2c8cf2285'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('company_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recruiter_name', sa.String(length=255), nullable=False),
    sa.Column('office_locations', sa.JSON(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_profiles_user_id'), 'company_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_company_profiles_verification_status'), 'company_profiles', ['verification_status'], unique=False)
    op.create_table('email_action_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_action_tokens_expires_at'), 'email_action_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_email_action_tokens_purpose'), 'email_action_tokens', ['purpose'], unique=False)
    op.create_index(op.f('ix_email_action_tokens_token_hash'), 'email_action_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_action_tokens_user_id'), 'email_action_tokens', ['user_id'], unique=False)
    op.create_table('institution_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('institution_code', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('departments', sa.JSON(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_profiles_institution_code'), 'institution_profiles', ['institution_code'], unique=True)
    op.create_index(op.f('ix_institution_profiles_user_id'), 'institution_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_institution_profiles_verification_status'), 'institution_profiles', ['verification_status'], unique=False)
    op.create_table('platform_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('reservation_policy', sa.JSON(), nullable=False),
    sa.Column('allow_reserved_seat_conversion', sa.Boolean(), nullable=False),
    sa.Column('minimum_profile_completion', sa.Integer(), nullable=False),
    sa.Column('minimum_required_skill_coverage', sa.Float(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_sessions_expires_at'), 'refresh_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_sessions_public_id'), 'refresh_sessions', ['public_id'], unique=True)
    op.create_index(op.f('ix_refresh_sessions_token_hash'), 'refresh_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False)
    op.create_table('academician_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_profile_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('host_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_expertise', sa.JSON(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_profile_id'], ['institution_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academician_opportunities_institution_profile_id'), 'academician_opportunities', ['institution_profile_id'], unique=False)
    op.create_table('academician_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_profile_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=False),
    sa.Column('expertise', sa.JSON(), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_profile_id'], ['institution_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academician_profiles_institution_profile_id'), 'academician_profiles', ['institution_profile_id'], unique=False)
    op.create_index(op.f('ix_academician_profiles_user_id'), 'academician_profiles', ['user_id'], unique=True)
    op.create_table('curriculum_insight_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_profile_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('algorithm_version', sa.String(length=40), nullable=False),
    sa.Column('source_summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_profile_id'], ['institution_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_insight_runs_institution_profile_id'), 'curriculum_insight_runs', ['institution_profile_id'], unique=False)
    op.create_table('industry_learning_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.String(length=80), nullable=False),
    sa.Column('resource_url', sa.String(length=500), nullable=False),
    sa.Column('badge_title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_profile_id'], ['company_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_learning_programs_company_profile_id'), 'industry_learning_programs', ['company_profile_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_profile_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('preferred_skills', sa.JSON(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('stipend', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('work_mode', sa.String(length=32), nullable=False),
    sa.Column('min_cgpa', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('moderation_status', sa.String(length=32), nullable=False),
    sa.Column('duration', sa.String(length=80), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reservation_policy', sa.JSON(), nullable=False),
    sa.Column('reservation_policy_approved', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_profile_id'], ['company_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_company_profile_id'), 'opportunities', ['company_profile_id'], unique=False)
    op.create_index(op.f('ix_opportunities_deadline'), 'opportunities', ['deadline'], unique=False)
    op.create_index(op.f('ix_opportunities_moderation_status'), 'opportunities', ['moderation_status'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_profile_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('college', sa.String(length=255), nullable=False),
    sa.Column('university', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=False),
    sa.Column('current_year', sa.Integer(), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('reservation_category', sa.String(length=32), nullable=False),
    sa.Column('reservation_status', sa.String(length=32), nullable=False),
    sa.Column('reservation_source', sa.String(length=255), nullable=False),
    sa.Column('reservation_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('projects', sa.JSON(), nullable=False),
    sa.Column('certifications', sa.JSON(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('general_pool_opt_in', sa.Boolean(), nullable=False),
    sa.Column('profile_completion', sa.Integer(), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=False),
    sa.Column('resume_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_profile_id'], ['institution_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_profiles_institution_profile_id'), 'student_profiles', ['institution_profile_id'], unique=False)
    op.create_index(op.f('ix_student_profiles_reservation_status'), 'student_profiles', ['reservation_status'], unique=False)
    op.create_index(op.f('ix_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=True)
    op.create_table('academician_opportunity_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academician_profile_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['academician_profile_id'], ['academician_profiles.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['academician_opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academician_profile_id', 'opportunity_id', name='uq_academic_application')
    )
    op.create_index(op.f('ix_academician_opportunity_applications_academician_profile_id'), 'academician_opportunity_applications', ['academician_profile_id'], unique=False)
    op.create_index(op.f('ix_academician_opportunity_applications_opportunity_id'), 'academician_opportunity_applications', ['opportunity_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('student_profile_id', sa.Integer(), nullable=True),
    sa.Column('company_profile_id', sa.Integer(), nullable=True),
    sa.Column('institution_profile_id', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(length=120), nullable=False),
    sa.Column('responsibility', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_profile_id'], ['company_profiles.id'], ),
    sa.ForeignKeyConstraint(['institution_profile_id'], ['institution_profiles.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_actor_user_id'), 'agent_runs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_agent_name'), 'agent_runs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_runs_company_profile_id'), 'agent_runs', ['company_profile_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_institution_profile_id'), 'agent_runs', ['institution_profile_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_student_profile_id'), 'agent_runs', ['student_profile_id'], unique=False)
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('category_slot', sa.String(length=32), nullable=False),
    sa.Column('algorithm_version', sa.String(length=40), nullable=False),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('decision_snapshot', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'student_profile_id', name='uq_allocation_opportunity_student')
    )
    op.create_index(op.f('ix_allocations_opportunity_id'), 'allocations', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_allocations_status'), 'allocations', ['status'], unique=False)
    op.create_index(op.f('ix_allocations_student_profile_id'), 'allocations', ['student_profile_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('preference_rank', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_profile_id', 'opportunity_id', name='uq_application_student_opportunity')
    )
    op.create_index(op.f('ix_applications_opportunity_id'), 'applications', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_applications_student_profile_id'), 'applications', ['student_profile_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('institution_profile_id', sa.Integer(), nullable=True),
    sa.Column('company_profile_id', sa.Integer(), nullable=True),
    sa.Column('student_profile_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_profile_id'], ['company_profiles.id'], ),
    sa.ForeignKeyConstraint(['institution_profile_id'], ['institution_profiles.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_company_profile_id'), 'audit_events', ['company_profile_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_institution_profile_id'), 'audit_events', ['institution_profile_id'], unique=False)
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_events_student_profile_id'), 'audit_events', ['student_profile_id'], unique=False)
    op.create_table('curriculum_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('institution_profile_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=False),
    sa.Column('skill', sa.String(length=120), nullable=False),
    sa.Column('gap_percent', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_profile_id'], ['institution_profiles.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['curriculum_insight_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_insights_department'), 'curriculum_insights', ['department'], unique=False)
    op.create_index(op.f('ix_curriculum_insights_institution_profile_id'), 'curriculum_insights', ['institution_profile_id'], unique=False)
    op.create_index(op.f('ix_curriculum_insights_run_id'), 'curriculum_insights', ['run_id'], unique=False)
    op.create_index(op.f('ix_curriculum_insights_skill'), 'curriculum_insights', ['skill'], unique=False)
    op.create_table('digital_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('credential_url', sa.String(length=500), nullable=False),
    sa.Column('evidence_url', sa.String(length=500), nullable=False),
    sa.Column('credential_id', sa.String(length=120), nullable=False),
    sa.Column('standards', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digital_badges_reviewed_by_user_id'), 'digital_badges', ['reviewed_by_user_id'], unique=False)
    op.create_index(op.f('ix_digital_badges_student_profile_id'), 'digital_badges', ['student_profile_id'], unique=False)
    op.create_index(op.f('ix_digital_badges_verification_status'), 'digital_badges', ['verification_status'], unique=False)
    op.create_table('learning_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource_url', sa.String(length=500), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_recommendations_student_profile_id'), 'learning_recommendations', ['student_profile_id'], unique=False)
    op.create_table('lsrw_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('listening', sa.Float(), nullable=False),
    sa.Column('speaking', sa.Float(), nullable=False),
    sa.Column('reading', sa.Float(), nullable=False),
    sa.Column('writing', sa.Float(), nullable=False),
    sa.Column('overall', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lsrw_assessments_student_profile_id'), 'lsrw_assessments', ['student_profile_id'], unique=False)
    op.create_table('match_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('skill_score', sa.Float(), nullable=False),
    sa.Column('required_coverage', sa.Float(), nullable=False),
    sa.Column('communication_score', sa.Float(), nullable=False),
    sa.Column('project_score', sa.Float(), nullable=False),
    sa.Column('academic_score', sa.Float(), nullable=False),
    sa.Column('location_score', sa.Float(), nullable=False),
    sa.Column('preference_score', sa.Float(), nullable=False),
    sa.Column('portfolio_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=40), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_profile_id', 'opportunity_id', name='uq_match_student_opportunity')
    )
    op.create_index(op.f('ix_match_results_opportunity_id'), 'match_results', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_match_results_student_profile_id'), 'match_results', ['student_profile_id'], unique=False)
    op.create_index(op.f('ix_match_results_total_score'), 'match_results', ['total_score'], unique=False)
    op.create_table('company_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('improvement_skills', sa.JSON(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.Column('recommend_for_placement', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('allocation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_feedback')
    op.drop_index(op.f('ix_match_results_total_score'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_student_profile_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_opportunity_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_index(op.f('ix_lsrw_assessments_student_profile_id'), table_name='lsrw_assessments')
    op.drop_table('lsrw_assessments')
    op.drop_index(op.f('ix_learning_recommendations_student_profile_id'), table_name='learning_recommendations')
    op.drop_table('learning_recommendations')
    op.drop_index(op.f('ix_digital_badges_verification_status'), table_name='digital_badges')
    op.drop_index(op.f('ix_digital_badges_student_profile_id'), table_name='digital_badges')
    op.drop_index(op.f('ix_digital_badges_reviewed_by_user_id'), table_name='digital_badges')
    op.drop_table('digital_badges')
    op.drop_index(op.f('ix_curriculum_insights_skill'), table_name='curriculum_insights')
    op.drop_index(op.f('ix_curriculum_insights_run_id'), table_name='curriculum_insights')
    op.drop_index(op.f('ix_curriculum_insights_institution_profile_id'), table_name='curriculum_insights')
    op.drop_index(op.f('ix_curriculum_insights_department'), table_name='curriculum_insights')
    op.drop_table('curriculum_insights')
    op.drop_index(op.f('ix_audit_events_student_profile_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_institution_profile_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_company_profile_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_applications_student_profile_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_opportunity_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_allocations_student_profile_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_status'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_opportunity_id'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_agent_runs_student_profile_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_institution_profile_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_company_profile_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_name'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_actor_user_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_academician_opportunity_applications_opportunity_id'), table_name='academician_opportunity_applications')
    op.drop_index(op.f('ix_academician_opportunity_applications_academician_profile_id'), table_name='academician_opportunity_applications')
    op.drop_table('academician_opportunity_applications')
    op.drop_index(op.f('ix_student_profiles_user_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_reservation_status'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_institution_profile_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_moderation_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_deadline'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_company_profile_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_industry_learning_programs_company_profile_id'), table_name='industry_learning_programs')
    op.drop_table('industry_learning_programs')
    op.drop_index(op.f('ix_curriculum_insight_runs_institution_profile_id'), table_name='curriculum_insight_runs')
    op.drop_table('curriculum_insight_runs')
    op.drop_index(op.f('ix_academician_profiles_user_id'), table_name='academician_profiles')
    op.drop_index(op.f('ix_academician_profiles_institution_profile_id'), table_name='academician_profiles')
    op.drop_table('academician_profiles')
    op.drop_index(op.f('ix_academician_opportunities_institution_profile_id'), table_name='academician_opportunities')
    op.drop_table('academician_opportunities')
    op.drop_index(op.f('ix_refresh_sessions_user_id'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_token_hash'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_public_id'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_expires_at'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_table('platform_policies')
    op.drop_index(op.f('ix_institution_profiles_verification_status'), table_name='institution_profiles')
    op.drop_index(op.f('ix_institution_profiles_user_id'), table_name='institution_profiles')
    op.drop_index(op.f('ix_institution_profiles_institution_code'), table_name='institution_profiles')
    op.drop_table('institution_profiles')
    op.drop_index(op.f('ix_email_action_tokens_user_id'), table_name='email_action_tokens')
    op.drop_index(op.f('ix_email_action_tokens_token_hash'), table_name='email_action_tokens')
    op.drop_index(op.f('ix_email_action_tokens_purpose'), table_name='email_action_tokens')
    op.drop_index(op.f('ix_email_action_tokens_expires_at'), table_name='email_action_tokens')
    op.drop_table('email_action_tokens')
    op.drop_index(op.f('ix_company_profiles_verification_status'), table_name='company_profiles')
    op.drop_index(op.f('ix_company_profiles_user_id'), table_name='company_profiles')
    op.drop_table('company_profiles')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
